### PR TITLE
GeoJSON

### PR DESCRIPTION
**Pull request by sroberts**
@gjtorikian I looked at this data and my first thought was "I wonder where all those monuments are." and so I decided to try to fix it. Here's that data. 

This was all done using a very ugly/hacky Python script using [Google's GeoCoding API](https://developers.google.com/maps/documentation/geocoding/intro). It's far from perfect. Certain types, like streets, were always causing errors. The rest were 50/50. But it's a start. 

Thanks for doing this. Even I didn't imagine how many of these things there were and how spread out they are. Hopefully this helps some folks see how bad it is.

### CODE REVIEW

**Comment by sroberts** [comment]
Don't merge this yet. I made a last change and it seems to have broken something.

**Comment by sroberts** [comment]
Should be good to go. :+1:

**Comment by gjtorikian** [comment]
Thanks for doing this!

I think some of the data might be missing... for example, I noticed that _arizona.geojson_ has two entries, but the CSV [has three](https://github.com/gjtorikian/destroy-all-monuments/blob/e81c646d3233d7876d94f05011cb07eb28027b2f/csv/arizona.csv). Do you know why this might be? (I didn't look at any of the others.)

**Comment by sroberts** [comment]
@gjtorikian Yeah, I didn't write the ones that Google Geocoding didn't give me an answer for. It's only about 2/5ths of the total. I played around with the quality a lot, but honestly this was the best I could get. About 50% came back without any data, and so with a few errors we got what we got.

**Comment by gjtorikian** [comment]
Good enough for me~

**Pull request merged**
